#!/usr/bin/env python

import sys
from binascii import a2b_hex

lns = sys.stdin.read()          # file as one string
lns = lns.replace('=\n', '')    # join marked lines
L = lns.split('=')              # put hex numbers at begin of elements 1,2,...
ll = map(lambda x: '%s%s' % (a2b_hex(x[:2]), x[2:]), L[1:])
                                # replace hex numbers by characters
print ''.join([L[0]]+ll)
