" vimrc, R.Wobst, 6.12.2003

set nocompatible
set autoindent
set shiftwidth=1
set showmode
set showmatch
set showcmd
set ruler
set nojoinspaces
set cpo+=$
set whichwrap=""
set modelines=0
colorscheme peachpuff
set term=linux

filetype plugin indent on
syntax enable
hi DiffAdd ctermfg=Gray
let python_highlight_all = 1

cmap <F9> w ! cat - >~/p<CR>
nmap <F10> :r ~/p<CR>
nmap <F11> <C-]>

" ~/.vimrc ends here
